export const PRODUCTS = [
  {
    "title": "Elixir Serum Ageless Skin",
    "img": "assets/img/products/elixirserumagelessskin.jpg",
    "price": "30.00 KM",
    "desc": "Elixir serum je luksuzni prirodni pro-age serum formulisan za dubinsku regeneraciju, hidrataciju i zaštitu kože koja s vremenom postaje zahtjevnija.\n\n                  Njegova pažljivo izbalansirana kombinacija dragocjenih biljnih ulja, skvalana i koenzima Q10 podržava prirodne procese obnove kože, vraćajući joj elastičnost, mekoću i zdrav sjaj.\n                  ## Šta Elixir serum čini jedinstvenim::\n                  ✨ Dubinska hidratacija i hranjenje kože  \n                  Ulje argana, badema i jojobe obnavlja hidrolipidnu barijeru kože, pružajući dugotrajnu hidrataciju, mekoću i svilenkast osjećaj – bez masnog traga.\n\n                  ✨ Pro-age zaštita i regeneracija  \n                  Ulje nara, bogato snažnim antioksidansima, štiti kožu od slobodnih radikala, podržava obnovu ćelija i doprinosi ublažavanju vidljivih znakova starenja.\n\n                  ✨ Povećana elastičnost i ujednačen ten  \n                  Ulje pulpe vučjeg trna intenzivno regenerira kožu, poboljšava teksturu i doprinosi zdravom, svježem izgledu, dok koenzim Q10 pomaže očuvanju energije ćelija i čvrstoće kože.\n\n                  ✨ Lagana, ali bogata tekstura  \n                  Serum se brzo upija, ne opterećuje kožu i savršeno se uklapa u svakodnevnu rutinu njege, samostalno ili ispod kreme.\n\n                  Serum je namijenjen zreloj, suhoj i dehidriranoj koži, kao i koži kojoj je potrebna regenerativna i pro-age njega. Idealan je za svakodnevnu upotrebu, u jutarnjoj i večernjoj rutini.\n                  ## Prirodna formulacija::\n                  Bez parabena, silikona, mineralnih ulja i sintetičkih mirisa.  \n                  Nije testirano na životinjama.\n                  ## Način upotrebe::\n                  Nanesite nekoliko kapi seruma na čistu kožu lica i vrata.\n\n                  Nježno umasirajte kružnim pokretima dok se potpuno ne upije.\n\n                  Koristiti ujutro i/ili navečer, samostalno ili prije kreme, u zavisnosti od potreba kože."
  },
  {
    "title": "Night Cream",
    "img": "assets/img/products/nightcream.jpg",
    "price": "30.00 KM",
    "desc": "Noćna krema je bogata, ali nježna prirodna formulacija osmišljena da podrži prirodne procese obnove kože tokom noći.\n\n                    Pažljivo izabrani aktivni sastojci djeluju sinergijski kako bi poboljšali elastičnost kože, umanjili znakove starenja i ojačali zaštitnu barijeru.\n                    ## Šta noćnu kremu čini posebnom::\n                    ✨ Regeneracija i učvršćivanje kože  \n                    Peptidi podstiču sintezu kolagena i elastina, doprinoseći čvršćoj, zaglađenoj koži i smanjenju vidljivosti bora.\n\n                    ✨ Antioksidativna zaštita i obnova  \n                    Koenzim Q10 štiti kožu od oksidativnog stresa, podržava ćelijsku regeneraciju i pomaže u očuvanju mladalačkog izgleda.\n\n                    ✨ Dubinska njega i hidratacija  \n                    Biljna ulja argana, skvalana i vučjeg trna, u kombinaciji sa shea buterom, hrane kožu, obnavljaju hidrolipidnu barijeru i vraćaju prirodan sjaj i mekoću.\n                    ## Namjena::\n                    Namijenjena svim tipovima kože, posebno zreloj, suhoj i koži kojoj je potrebna intenzivna regeneracija i pro-age njega.\n\n                    Idealna za večernju rutinu njege.\n                    ## Prirodna formulacija::\n                    Bez parabena, silikona, mineralnih ulja i sintetičkih mirisa.  \n                    Nije testirano na životinjama."
  },
  {
    "title": "Hydrating Cream",
    "img": "assets/img/products/hydratingcream.jpg",
    "price": "25.00 KM",
    "desc": "Hidratantna krema pažljivo je formulisana kako bi koži pružila optimalnu hidrataciju, ojačala njenu prirodnu barijeru i osigurala dugotrajan osjećaj ugode tokom dana. Lagana, svilenkasta tekstura brzo se upija i ostavlja kožu mekom, elastičnom i prirodno blistavom – bez osjećaja težine.\n\n                    Formulacija je osmišljena da podrži zdravlje kože, smanji osjetljivost i očuva ujednačen i svjež izgled tena.\n                    ## Šta hidratantnu kremu čini posebnom::\n                    ✨ Dubinska hidratacija i jačanje kožne barijere  \n                    Prirodne masne kiseline iz ulja avokada, u kombinaciji s ceramidima, pomažu obnovi hidrolipidne barijere, sprječavaju gubitak vlage i doprinose dugotrajnoj mekoći i elastičnosti kože.\n\n                    ✨ Ujednačen i smiren ten  \n                    Vitamin B3 (niacinamid) reguliše lučenje sebuma, umiruje kožu sklonu iritacijama i pomaže u smanjenju neujednačenosti tena.\n\n                    ✨ Umirujuća i osvježavajuća njega  \n                    Aloe vera gel umiruje crvenilo, obnavlja kožu i pruža osjećaj svježine i ugode.\n                    ## Namjena::\n                    Pogodna za sve tipove kože, uključujući osjetljivu, dehidriranu i kožu s narušenom barijernom funkcijom.\n\n                    Idealna za svakodnevnu upotrebu, u jutarnjoj i večernjoj rutini njege.\n                    ## Prirodna formulacija::\n                    Bez parabena, silikona, mineralnih ulja i sintetičkih mirisa.  \n                    Nije testirano na životinjama."
  },
  {
    "title": "Anti Acne Cream",
    "img": "assets/img/products/antiacnecream.jpg",
    "price": "30.00 KM",
    "desc": "Anti-Acne krema pažljivo je formulisana za njegu problematične, masne i mješovite kože sklone aknama i nepravilnostima. Lagana, brzo upijajuća tekstura djeluje ciljano na uzroke problema, bez isušivanja i narušavanja prirodne ravnoteže kože.\n\n                  Formulacija je osmišljena da istovremeno reguliše lučenje sebuma, umiri iritacije i podrži prirodnu obnovu kože, ostavljajući ten čistim, ujednačenim i njegovanog izgleda.\n                  ## Kako Anti-Acne krema djeluje?::\n                  ✨ Kontroliše sebum i čisti pore  \n                  Niacinamid (vitamin B3) reguliše lučenje sebuma, smanjuje vidljivost pora i poboljšava teksturu kože. Doprinosi uravnoteženijem tenu i pomaže u prevenciji nastanka novih nepravilnosti, bez osjećaja zatezanja ili suhoće.\n\n                  ✨ Umiruje i obnavlja kožu  \n                  Alantoin djeluje umirujuće i regenerativno, smanjuje crvenilo i iritacije te pomaže koži da se brže oporavi, što je posebno važno kod kože sklone upalnim procesima.\n\n                  ✨ Podrška zdravlju problematične kože  \n                  Vitamin A podržava prirodnu obnovu kože i doprinosi ujednačenijem izgledu tena, dok ekstrakt irisa pomaže u balansiranju kože sklone nepravilnostima i očuvanju njenog svježeg, čistog izgleda.\n                  ## Način upotrebe::\n                  Nanijeti malu količinu kreme na čistu i suhu kožu lica, nježno umasirati dok se potpuno ne upije.\n\n                  Koristiti ujutro i uvečer.\n                  ## Prirodna formulacija::\n                  Bez parabena, silikona, mineralnih ulja i agresivnih sastojaka.\n\n                  Formulisana s pažljivo biranim aktivnim sastojcima koji poštuju prirodnu ravnotežu kože."
  },
  {
    "title": "Natural Glow Serum",
    "img": "assets/img/products/naturalglowserum.jpg",
    "price": "25.00 KM",
    "desc": "Natural Glow serum je lagani, nemasni uljni serum formulisan za svakodnevnu njegu kože kojoj je potrebna hidratacija, ravnoteža i zdrav, prirodan sjaj. Pažljivo izabrana kombinacija biljnih ulja i skvalana dubinski njeguje kožu, jača njenu prirodnu barijeru i ostavlja osjećaj mekoće i ugode.\n\n                    Svilenkasta tekstura brzo se upija i čini kožu glatkom, njegovanom i blistavom – bez masnog traga.\n                    ## Šta Natural Glow serum donosi vašoj koži?::\n                    ✨ Dubinska njega i antioksidativna zaštita  \n                    Ulje avokada i ulje sjemenki grožđa bogati su antioksidansima koji pomažu u regeneraciji kože i štite je od vanjskih utjecaja.\n\n                    ✨ Hidratacija i jačanje kožne barijere  \n                    Skvalan i ulje jojobe pomažu u očuvanju optimalnog nivoa vlage, jačaju hidrolipidnu barijeru i doprinose elastičnosti kože.\n\n                    ✨ Ujednačen i svjež ten  \n                    Ulje mrkve doprinosi ujednačenijem tenu, osvježava kožu i daje joj prirodan, zdrav sjaj.\n                    ## Namjena::\n                    Pogodan za sve tipove kože, uključujući normalnu, mješovitu i dehidriranu kožu.\n\n                    Idealan za svakodnevnu upotrebu, u jutarnjoj i večernjoj rutini njege, samostalno ili u kombinaciji s kremom.\n                    ## Prirodna formulacija::\n                    Bez parabena, silikona, mineralnih ulja i sintetičkih mirisa.  \n                    Nije testirano na životinjama."
  },
  {
    "title": "Face Cleansing Foam",
    "img": "assets/img/products/facecleansingfoam.jpg",
    "price": "18.00 KM",
    "desc": "Magnolia nježna pjena za čišćenje lica formulirana je kako bi učinkovito uklonila nečistoće i višak sebuma, a pritom sačuvala prirodnu ravnotežu i zaštitnu barijeru kože. Lagana, pjenasta tekstura čisti bez isušivanja i ostavlja kožu svježom, mekom i umirenom nakon svakog korištenja.\n\n                    Idealna je kao prvi korak jutarnje i večernje skincare rutine, čak i za osjetljivu kožu.\n                    ## Nježno čišćenje koje poštuje vašu kožu::\n                    ✨ Blago, ali učinkovito čišćenje  \n                    Prirodni surfaktanti temeljito uklanjaju nečistoće bez oštećenja zaštitnog sloja kože.\n\n                    ✨ Jačanje kožne barijere i hidratacija  \n                    Ceramidi pomažu u očuvanju prirodne barijere kože, sprječavaju gubitak vlage i doprinose osjećaju ugode i mekoće nakon čišćenja.\n\n                    ✨ Umirenje i svježina  \n                    Pantenol (provitamin B5) i aloe vera djeluju umirujuće, smanjuju crvenilo i podržavaju prirodnu regeneraciju kože.\n                    ## Za koga je namijenjena?::\n                    Pogodna za sve tipove kože, posebno za suhu, osjetljivu i kožu s narušenom barijernom funkcijom.\n\n                    Namijenjena je svakodnevnoj upotrebi, ujutro i uvečer, za nježno, ali temeljito čišćenje lica – bez osjećaja zatezanja.\n                    ## Prirodna formulacija::\n                    Bez alkohola, sulfata, parabena i mirisa.  \n                    Nije testirano na životinjama.\n\n                    🫧 Lagane pjenaste teksture – čisti, hidrira i jača barijeru kože 🫧"
  },
  {
    "title": "Makeup Removal Milk",
    "img": "assets/img/products/makeupremovalmilk.jpg",
    "price": "12.00 KM",
    "desc": "Mlijeko za skidanje šminke na bazi ulja slatkog badema i pantenola nježno, ali učinkovito uklanja šminku i nečistoće, bez isušivanja i narušavanja prirodne ravnoteže kože. Kremasta, ugodna tekstura ostavlja kožu čistom, mekanom i umirenom nakon svakog korištenja.\n\n                    Formulisano je da istovremeno čisti i njeguje kožu, čineći ga idealnim izborom za svakodnevnu rutinu njege, čak i za osjetljivu kožu.\n                    ## Čistoća i njega u jednom koraku::\n                    ✨ Temeljna, ali nježna njega kože  \n                    Ulje slatkog badema bogato vitaminima A i E djeluje antioksidativno, štiti kožu od vanjskih utjecaja i ostavlja je svilenkasto mekom i nahranjenom.\n\n                    ✨ Obnavljajuća hidratacija i umirenje  \n                    Pantenol (provitamin B5) prodire u dublje slojeve kože, smiruje iritacije, podržava regeneraciju i doprinosi dugotrajnoj hidrataciji.\n\n                    ✨ Čistoća bez agresivnih sastojaka  \n                    Blaga, prirodna formulacija ne narušava kožnu barijeru i pruža osjećaj svježine i ugode nakon svakog čišćenja.\n                    ## Namjena::\n                    Pogodno za sve tipove kože, posebno za osjetljivu, suhu i dehidriranu kožu.\n\n                    Namijenjeno svakodnevnoj upotrebi, u jutarnjoj i večernjoj rutini njege.\n                    ## Prirodna formulacija::\n                    Bez parabena, sulfata, silikona i vještačkih mirisa.  \n                    Nije testirano na životinjama."
  },
  {
    "title": "Njega Usana",
    "img": "assets/img/products/njegausana.jpg",
    "price": "7.00 KM",
    "desc": "Naš Lip Balm formuliran je na potpuno prirodnoj bazi, s pažljivo biranim biljnim uljima i puterima koji intenzivno hrane, omekšavaju i štite usne. Pomaže u očuvanju prirodne vlažnosti i pruža dugotrajan osjećaj ugode, bez težine na usnama.\n\n                    Formulacija, obogaćena eteričnim uljem slatke naranče, usnama daje blag, prirodan miris i ugodan osjećaj svježine pri svakom nanošenju.\n                    ## Prednosti::\n                    ✨ Intenzivna hidratacija i svakodnevna njega  \n                    ✨ Zaštita od isušivanja i vanjskih uticaja  \n                    ✨ Mekane, glatke i prirodno njegovane usne  \n                    ✨ Formulacija na bazi biljnih ulja i putera  \n                    ## Način upotrebe::\n                    Nanesite tanki sloj balzama na usne po potrebi, tokom dana ili uvečer.\n\n                    Može se koristiti samostalno ili kao podloga prije nanošenja ruža.\n                    ## Zašto odabrati ovaj Lip Balm?::\n                    Savršen izbor za zdrave, njegovane i prirodno lijepe usne – svaki dan."
  },
  {
    "title": "Hair Growth Serum",
    "img": "assets/img/products/hairgrowthserum.jpg",
    "price": "35.00 KM",
    "desc": "Magnolia Hair Growth serum pažljivo je formulisan kako bi ciljano djelovao na vlasište i folikule kose, smanjujući opadanje i potičući rast novih, snažnijih vlasi.\n\n                  Lagana, nemasna tekstura lako se upija, ne opterećuje kosu i pogodna je za redovnu upotrebu, dok sinergija aktivnih sastojaka jača kosu od korijena do vrhova i doprinosi gušćoj, otpornijoj i zdravijoj kosi.\n                  ## Zašto Hair Growth serum djeluje::\n                  ✨ Stimulacija rasta i jačanje folikula  \n                  Kofein potiče mikrocirkulaciju u vlasištu, aktivira folikule i produžava fazu rasta dlake, doprinoseći vidljivo gušćoj i snažnijoj kosi.\n\n                  ✨ Obnova strukture i otpornost vlasi  \n                  Keratin jača strukturu dlake, smanjuje lomljenje i vraća elastičnost, čineći kosu otpornijom, zaglađenom i sjajnijom.\n\n                  ✨ Balans i njega vlasišta  \n                  Niacinamid (vitamin B3) jača barijernu funkciju vlasišta, pomaže u regulaciji masnoće, smanjuje iritacije i podržava zdrav rast kose.\n\n                  ✨ Dubinska hidratacija i regeneracija  \n                  Hijaluronska kiselina intenzivno hidrira vlasište, sprječava isušivanje i doprinosi fleksibilnosti i vitalnosti vlasi.\n\n                  ✨ Prirodna podrška gustini kose  \n                  Ekstrakt preslice, bogat silicijem i mineralima, jača folikule, podstiče sintezu kolagena i doprinosi snažnijoj, otpornijoj i gušćoj kosi.\n\n                  Serum je namijenjen svim tipovima kose, posebno tankoj, oslabljenoj i kosi sklonoj opadanju i lomljenju. Idealan je za redovnu upotrebu uz masažu vlasišta.\n                  ## Prirodna formulacija:: \n                  Bez parabena, silikona i agresivnih sastojaka.  \n                  Nije testirano na životinjama.\n                  ## Način upotrebe::\n                  Pomoću pipete nanijeti nekoliko kapi seruma direktno na čisto vlasište.\n                  Nježno umasirati vrhovima prstiju.\n\n                  Ne ispirati.\n\n                  Koristiti dva do tri puta sedmično ili po potrebi, u kontinuitetu za optimalne rezultate."
  },
  {
    "title": "Hair Oil Serum",
    "img": "assets/img/products/hairoilserum.jpg",
    "price": "25.00 KM",
    "desc": "Magnolia Hair Oil serum bogate, ali lagane teksture formulisan je kako bi dubinski nahranio kosu, zagladio vlasi i pružio dugotrajan prirodan sjaj bez osjećaja težine.\n\n                  Pažljivo odabrana kombinacija biljnih ulja štiti kosu od isušivanja, lomljenja i vanjskih utjecaja, ostavljajući je mekom, podatnom i njegovanom.\n                  ## Zašto Hair Oil serum djeluje?::\n                  ✨ Dubinska ishrana i obnova vlasi  \n                  Ulje argana i ulje makadamije bogati su esencijalnim masnim kiselinama i vitaminom E, obnavljaju strukturu vlasi, jačaju kosu i vraćaju joj mekoću i vitalnost.\n\n                  ✨ Zaglađivanje i prirodan sjaj  \n                  Kokosovo ulje pomaže u zaglađivanju kutikule, smanjuje gubitak proteina i doprinosi sjajnoj, glatkoj i zdravoj kosi.\n\n                  ✨ Zaštita od isušivanja i lomljenja  \n                  Formulacija štiti kosu od gubitka vlage, mehaničkih oštećenja i nepovoljnih vanjskih utjecaja.\n\n                  ✨ Njega bez otežavanja  \n                  Svilenkasta, nemasna tekstura brzo se upija, ne masti kosu i pogodna je za svakodnevnu upotrebu.\n                  ## Način upotrebe::\n                  Nanijeti nekoliko kapi seruma na dlanove, zatim ravnomjerno rasporediti na dužinu i vrhove kose.\n\n                  Može se koristiti na vlažnoj kosi prije sušenja ili na suhoj kosi za dodatni sjaj i zaglađivanje.\n\n                  Po potrebi, može se koristiti i kao uljni tretman prije pranja – nanijeti na kosu i ostaviti da djeluje 20–30 minuta, zatim oprati kosu blagim šamponom.\n                  ## Prirodna formulacija::\n                  100% prirodna formula.  \n                  Bez parabena, silikona i mineralnih ulja.  \n                  Nije testirano na životinjama."
  },
  {
    "title": "Vital Hair Mask",
    "img": "assets/img/products/vitalhairmask.jpg",
    "price": "100ml - 15.00 KM | 200ml - 25.00KM",
    "desc": "Magnolia Hair Mask je tretman za kosu formulisan da obnovi, ojača i nahrani kosu iznutra. Idealna je za kosu oštećenu čestom upotrebom toplinskih alata, boja ili spoljašnjim utjecajima, vraćajući joj snagu, elastičnost i prirodan sjaj.\n\n                    Bogata, ali lagana tekstura masku čini lako nanosivom i brzo upijajućom, bez otežavanja kose, čineći je mekom, glatkom i podatnom već nakon prvog korištenja.\n                    ## Zašto Hair Mask djeluje::\n                    ✨ Dubinska obnova kose s keratinom\n                    Nadoknađuje izgubljene proteine, obnavlja strukturu vlasi i čini kosu snažnom, glatkom i otpornijom na lomljenje.\n\n                    ✨ Hranjenje i zaštita s arganovim uljem\n                    Bogato vitaminom E i antioksidansima, arganovo ulje intenzivno hrani, omekšava i štiti kosu od isušivanja, vraćajući joj prirodan sjaj.\n\n                    ✨ Gušća i otpornija kosa s ricinusovim uljem\n                    Jača vlasi od korijena do vrhova, smanjuje lomljenje i doprinosi punijem i zdravijem izgledu kose.\n\n                    ✨ Hidratacija i elastičnost s pantenolom\n                    Zadržava vlagu unutar vlasi, čini kosu podatnom, mekanom i lakšom za oblikovanje.\n\n                    ✨ Green Plex kompleks – dodatna regeneracija\n                    Inovativni biljni kompleks dodatno štiti i jača strukturu kose, doprinoseći dugotrajnoj vitalnosti i otpornosti.\n                    ## Namjena::\n                    Pogodna za sve tipove kose, posebno suhoj, oštećenoj, farbanoj i lomljivoj kosi kojoj je potrebna dubinska njega i obnova.\n                    ## Način upotrebe::\n                    Nanesite masku na opranu, vlažnu kosu, ravnomjerno dužinom i na vrhove.\n\n                    Ostavite da djeluje 5–10 minuta, zatim temeljito isperite.\n\n                    Za dodatnu obnovu, ostavite masku 15 minuta uz blagu toplinu.\n\n                    Koristiti 1–2 puta sedmično.\n                    ## Prirodna formulacija::\n                    ✔ Bez parabena\n                    ✔ Bez silikona\n                    ✔ Bez sulfata\n                    ✔ Bez agresivnih sastojaka\n                    ✔ Nije testirano na životinjama"
  },
  {
    "title": "Vital Hair Shampoo",
    "img": "assets/img/products/vitalhairshamboo.jpg",
    "price": "20.00 KM",
    "desc": "Magnolia Vital Hair Shampoo pažljivo je formulisan kako bi vaša kosa bila snažna, podatna i zdrava, uz nježno čišćenje prirodnim surfaktantima.\n\n                  Lagana tekstura uklanja nečistoće i višak sebuma bez isušivanja, čineći kosu mekom, glatkom i svilenkastom, dok aktivni sastojci hrane vlas i pomažu očuvanju prirodne snage i sjaja kose.\n                  ## Zašto odabrati Vital Hair Shampoo::\n                  ✨ Jačanje i obnova strukture vlasi\n                  Keratin jača kosu iznutra, popunjava oštećenja vlasi i čini je otpornijom na lomljenje, pružajući dugotrajnu snagu i elastičnost.\n\n                  ✨ Svilenkasta mekoća i prirodan sjaj\n                  Proteini svile zaglađuju vlasi, vraćaju prirodan sjaj, omekšavaju kosu i olakšavaju raščešljavanje, čineći je glatkom i svilenkastom.\n\n                  ✨ Dubinska hidratacija i fleksibilnost\n                  Pantenol (provitamin B5) dubinski hidratizira, obnavlja vlagu unutar vlasi, povećava fleksibilnost kose i smanjuje lomljivost, pružajući zdrav i njegovan izgled.\n\n                  Ovaj šampon kombinira snagu prirodnih sastojaka i blagu formulu, čineći kosu snažnom, sjajnom i podatnom svakog dana.\n                  ## Prirodna formulacija::\n                  ✔ Prirodni sastojci\n                  ✔ Prirodni surfaktanti, bez sulfata\n                  ✔ Bez parabena\n                  ✔ Bez silikona\n                  ✔ Nije testirano na životinjama\n                  ## Način upotrebe::\n                  Nanesite na mokru kosu i nježno umasirajte u vlasište i dužinu kose.\n\n                  Temeljito isperite vodom.\n\n                  Po potrebi ponovite postupak.\n\n                  Pogodno za svakodnevnu upotrebu."
  },
  {
    "title": "Sun Tanning Oil",
    "img": "assets/img/products/suntanningoil.jpg",
    "price": "25.00 KM",
    "desc": "Prirodno ulje za sunčanje za blistav, ujednačen ten i njegu kože.\n\n                    ✨ Ljeto na koži — na najnježniji način\n\n                    Sun Tanning Oil je pažljivo formulisano prirodno ulje koje potiče postepeno, ujednačeno tamnjenje, dok istovremeno njeguje i štiti kožu od isušivanja tokom izlaganja suncu.\n\n                    Njegova lagana, svilenkasta tekstura brzo se upija, ostavljajući kožu mekom, elastičnom i blistavom, bez teškog ili masnog osjećaja.\n                    ## Snaga prirodnih sastojaka::\n                    Kombinacija pažljivo odabranih biljnih ulja i aktivnih sastojaka pruža koži sve što joj je potrebno tokom sunčanja:\n\n                    ✨ Macerat mrkve – potiče prirodno tamnjenje i daje zdrav sjaj koži  \n                    ✨ Ulje oraha – doprinosi toplijem, bronzanom tonu  \n                    ✨ Buriti ulje – bogato beta-karotenom i antioksidansima  \n                    ✨ Peptidni kompleks – podržava prirodne procese kože i ujednačen ten  \n                    ✨ Biljni antioksidansi – štite kožu od isušivanja i vanjskih utjecaja  \n\n                    Rezultat je koža koja ne samo da izgleda preplanulo — već i zdravo, njegovano i vitalno.\n                    ## Benefiti koje ćete primijetiti::\n                    ✨ Brže i prirodnije tamnjenje  \n                    ✨ Ujednačen, dugotrajan ten  \n                    ✨ Intenzivna hidratacija i mekoća kože  \n                    ✨ Svilenkast, luksuzan osjećaj na koži  \n                    ✨ Prirodan glow bez masnog traga  \n                    ## Kako koristiti::\n                    Nanijeti ravnomjerno na kožu prije izlaganja suncu.\n\n                    Po potrebi ponoviti tokom dana, posebno nakon kupanja.\n                    ## Napomena::\n                    Ne sadrži SPF zaštitu, preporučuje se kombinacija sa zaštitnim faktorom.\n                    ## Filozofija proizvoda::\n                    Bez parabena.  \n                    Bez silikona.  \n\n                    Formulisan s poštovanjem prema koži i prirodi."
  },
  {
    "title": "Shimmer Body Oil",
    "img": "assets/img/products/shimmerbodyoil.jpg",
    "price": "20.00 KM",
    "desc": "Luksuz u svakoj kapi, za kožu koja izgleda njegovano, blistavo i prirodno privlačno.\n\n                  Dubinski hrani i hidrira kožu, ostavljajući je svilenkastom i nježnom, dok je obavija toplim, zavodljivim mirisom vanilije.\n\n                  Obogaćen finim zlatnim shimmerom, naglašava preplanuli ten, dajući koži elegantan, zdrav sjaj bez osjećaja težine ili masnog traga.\n\n                  Savršen izbor za svaki dan kada želiš izgledati njegovanije i osjećati se posebno.\n\n                  Formula bazirana na pažljivo odabranim biljnim uljima i vitaminu E intenzivno hidrira, hrani i omekšava kožu. Lako se nanosi i brzo upija, pružajući ugodan, svilenkast osjećaj na koži.\n\n                  Topla vanilija i cvjetne note dodatno naglašavaju doživljaj njege – elegantno, ženstveno i nenametljivo.\n                  ## Zašto ćeš ga voljeti::\n                  ✨ Naglašava preplanuli ten i prirodni sjaj kože  \n                  ✨ Dubinski hidrira i hrani  \n                  ✨ Brzo se upija, bez masnog filma  \n                  ✨ Pruža svilenkast osjećaj na koži  \n                  ✨ Elegantan shimmer efekt za dan i večer  \n                  ## Način upotrebe::\n                  Nanijeti malu količinu na čistu, suhu kožu i lagano umasirati.\n\n                  Po potrebi ponoviti za intenzivniji sjaj.\n                  ## Prirodna formulacija::\n                  Bez parabena.  \n                  Bez sintetičkih boja.  \n\n                  Formulisano s pažnjom prema koži."
  },
  {
    "title": "Tanning Marmalade",
    "img": "assets/img/products/tanningmarmelade.jpg",
    "price": "25.00 KM",
    "desc": "Prirodna marmelada za intenzivan, ujednačen ten.\n\n                  ✨ Intenzivan ten uz dubinsku njegu\n\n                  Tanning Marmalade je bogata, hranjiva formula koja potiče brže i ujednačeno tamnjenje, dok istovremeno intenzivno njeguje i štiti kožu od isušivanja tokom sunčanja.\n\n                  Zahvaljujući pažljivo odabranim biljnim uljima, koža ostaje mekana, elastična i vidljivo blistava, uz prirodan bronzani sjaj.\n                  ## Ključni sastojci::\n                  ✨ Ulje mrkve – potiče prirodno tamnjenje i daje zdrav glow  \n                  ✨ Ulje oraha – doprinosi toplijem, bronzanom tonu  \n                  ✨ Kokosovo, maslinovo i ulje vučjeg trna – dubinski hrane i sprječavaju isušivanje  \n                  ## Prednosti::\n                  ✨ Brže i intenzivnije tamnjenje  \n                  ✨ Ujednačen i dugotrajan ten  \n                  ✨ Dubinska hidratacija i mekoća kože  \n                  ✨ Bogata, luksuzna tekstura koja se topi na koži  \n                  ## Upotreba::\n                  Nanijeti na kožu prije izlaganja suncu.\n\n                  Za dodatnu zaštitu koristiti zajedno sa SPF proizvodom.\n                  ## Napomena::\n                  Proizvod ne sadrži zaštitni faktor (SPF).\n                  ## Čista formulacija::\n                  Bez parabena i mineralnih ulja.\n\n                  100% prirodni sastojci u svakoj teglici."
  }
];
